//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calories
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// Autogenerated class containing Lists table definition
    /// </summary>
    public partial class Lists
    {
        /// <summary>
        /// Constructor of Lists DbSet
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lists()
        {
            this.ProductsLists = new HashSet<ProductsLists>();
        }
        /// <summary>
        /// Primary key for Lists table
        /// </summary>
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        /// <summary>
        /// Field containing name of list
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Creation date field in table
        /// </summary>
        public Nullable<System.DateTime> Creation_date { get; set; }
        /// <summary>
        /// List of all Products related to list
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsLists> ProductsLists { get; set; }
    }
}
