//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calories
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// Autogenerated class containing Products table definition
    /// </summary>
    public partial class Products
    {
        /// <summary>
        /// Constructor of ProductsLists DbSet
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsLists = new HashSet<ProductsLists>();
        }
        /// <summary>
        /// Primary key of Products table
        /// </summary>
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        /// <summary>
        /// Name of product 
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Field containg amount of calories of product
        /// </summary>
        public Nullable<int> calories { get; set; }
        /// <summary>
        /// Field containing weight of product
        /// </summary>
        public Nullable<int> weight { get; set; }
    
        /// <summary>
        /// Collection of all lists that contains product
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsLists> ProductsLists { get; set; }
    }
}
