//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsLists
    {
        public int Product_id { get; set; }
        public int List_id { get; set; }
        public int Amount { get; set; }
    
        public virtual Lists Lists { get; set; }
        public virtual Products Products { get; set; }
    }
}
