//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calories
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// List of products lists
    /// </summary>
    public partial class ProductsLists
    {
        /// <summary>
        /// One of primary key's field - reference to Products table
        /// </summary>
        public int Product_id { get; set; }
        /// <summary>
        /// One of primary key's field - reference to Lists table
        /// </summary>
        public int List_id { get; set; }
        /// <summary>
        /// Amount of product that is on specific list
        /// </summary>
        public int Amount { get; set; }
        /// <summary>
        /// List that is related to product
        /// </summary>
        public virtual Lists Lists { get; set; }
        /// <summary>
        /// Product related to list
        /// </summary>
        public virtual Products Products { get; set; }
    }
}
